### ISSUE TITLE
Disable buttons on answer or timeout, enable when a new question is displayed

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#5]
# What is the issue? 

- With v2 the feedback and new questions can take a second to load
- This means that people could click the button multiple times before a new question is displayed
- All of these clicks would get counted, resulting in more than 1 answer per question
- When the time is up it still takes some time to disaplay the new question, this can also result in 2 answers, 1 timout en 1 last minute click

## What to do about this? 

- HTML buttons have a property called [disabled (check an example here)](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_button_disabled)
- You can also [disable buttons on the fly using some JavaScript](https://flaviocopes.com/how-to-disable-button-javascript/)

## Todo

- [x] When an answer is submitted, select all buttons, loop through them and disable them (before awaiting the response!)
- [x] After a question is loaded, select all buttons, loop through them and _enable_ them
- [x] When the time is up, select all buttons, loop through them and disable them (before awaiting the response!)

**Comment by Reinoptland** [comment]
LGTM 👍
