### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Reinoptland** [karinhogenbirk/famousProgrammers#7]
# What 

Now that user can signup, we want to be able to login and get a token to authenticate users for followup requests without having to fill in the passwords again.

## How 

The user can go to `login.html` and see a login form. When they fill in the right information and submit the form, they will receive a token. If the email / password combination is not correct, we send back a error message and a error status  (something in the 4XX range)

## Todo

- [x] Create a login form
- [x] When the form is submitted, we send the info with a POST request /login or /auth/login (you decide) we send email and password
- [x] In the backend rout of POST /auth/login, find a user by their email
- [x] When the user found, use bcrypt to compare their password from the database (hash) with what is coming from the frontend (unhashed) 
- [x] If the password matches, create a JWT token that contains their userId, you can create JWT's with [jsonwebtoken](https://www.npmjs.com/package/jsonwebtoken)
- [x] Send the token to the frontend with a response
- [x] When email / password combination doesn't match send a 4XX response (check which one is most appropriate) with message like: email or password incorrect

## Bonus
- [x] In the frontend, await the response of the server, when the response is good, store the token in `localStorage`
- [x] Add an .env file and add .env to gitignore 
- [x] read the .env file on startuo with [dotenv](https://www.npmjs.com/package/dotenv)
- [x] The .env contains a "secret" string that you use to sign the tokens (a secret stamp!)
- [x] Use zod to validate the input to the request
